services:
  - docker

addons:
  hosts:
    - mkdocs

before_install:
  - docker --version
  - docker pull alpine:latest


jobs:
  include:
    - stage: build&test
      script:
        - docker build -t polinux/mkdocs:staging .
        - docker run -d --cap-add NET_ADMIN -p 8000:8000 --name mkdocs polinux/mkdocs:staging
        - sleep 10
        - curl -sSLi http://mkdocs:8000  | grep '200 OK'
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
        - docker push polinux/mkdocs:staging

    - stage: deploy
      if: branch = master
      script:
        - export RELEASE=$(grep "MKDOCS_VERSION=" Dockerfile | sed 's|^.*=||g' |awk '{print $1}' | sed 's|"||g')
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
        - docker pull polinux/mkdocs:staging
        - docker tag polinux/mkdocs:staging polinux/mkdocs:latest
        - docker tag polinux/mkdocs:staging polinux/mkdocs:${RELEASE}
        - docker push polinux/mkdocs:${RELEASE}
        - docker push polinux/mkdocs:latest