services:
  - docker

addons:
  hosts:
    - mkdocs

before_install:
  - docker --version
  - docker pull alpine:latest


jobs:
  include:
    - stage: build
      script:
        - docker build -t polinux/mkdocs:latest .

    - stage: run
      script:
        - docker run -d --cap-add NET_ADMIN -p 8000:8000 --name mkdocs polinux/mkdocs
        - sleep 10

    - stage: test
      script:
        - curl -sSLi http://mkdocs:8000  | grep '200 OK'

    - name: deploy
      if: branch = master
      script:
        - docker build -t polinux/mkdocs:$TRAVIS_TAG .
        - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
        - docker push polinux/mkdocs:$TRAVIS_TAG
        - docker push polinux/mkdocs:latest